"""anytask_scraper: Scrape course data from anytask.org."""

from anytask_scraper._logging import setup_logging
from anytask_scraper.client import AnytaskClient, DownloadResult, LoginError
from anytask_scraper.display import (
    display_course,
    display_gradebook,
    display_queue,
    display_submission,
    display_task_detail,
)
from anytask_scraper.models import (
    Comment,
    Course,
    FileAttachment,
    Gradebook,
    GradebookEntry,
    GradebookGroup,
    QueueEntry,
    QueueFilters,
    ReviewQueue,
    Submission,
    Task,
    filter_gradebook,
)
from anytask_scraper.parser import (
    extract_csrf_from_queue_page,
    extract_issue_id_from_breadcrumb,
    format_student_folder,
    parse_course_page,
    parse_gradebook_page,
    parse_queue_filters,
    parse_submission_page,
    parse_task_edit_page,
    strip_html,
)
from anytask_scraper.storage import (
    download_submission_files,
    save_course_csv,
    save_course_json,
    save_course_markdown,
    save_gradebook_csv,
    save_gradebook_json,
    save_gradebook_markdown,
    save_queue_csv,
    save_queue_json,
    save_queue_markdown,
    save_submissions_csv,
    save_submissions_json,
    save_submissions_markdown,
)

__all__ = [
    "AnytaskClient",
    "Comment",
    "Course",
    "DownloadResult",
    "FileAttachment",
    "Gradebook",
    "GradebookEntry",
    "GradebookGroup",
    "LoginError",
    "QueueEntry",
    "QueueFilters",
    "ReviewQueue",
    "Submission",
    "Task",
    "display_course",
    "display_gradebook",
    "display_queue",
    "display_submission",
    "display_task_detail",
    "download_submission_files",
    "extract_csrf_from_queue_page",
    "extract_issue_id_from_breadcrumb",
    "filter_gradebook",
    "format_student_folder",
    "parse_course_page",
    "parse_gradebook_page",
    "parse_queue_filters",
    "parse_submission_page",
    "parse_task_edit_page",
    "save_course_csv",
    "save_course_json",
    "save_course_markdown",
    "save_gradebook_csv",
    "save_gradebook_json",
    "save_gradebook_markdown",
    "save_queue_csv",
    "save_queue_json",
    "save_queue_markdown",
    "save_submissions_csv",
    "save_submissions_json",
    "save_submissions_markdown",
    "setup_logging",
    "strip_html",
]
